version: "3"
services:
  web:
    env_file:
      - .env
    build: .
    ports: ["80:8000"]
    volumes:
      - .:/app

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - hdoc_redis:/data

volumes:
  hdoc_redis:
